name: agent_py_env

dependencies:
  - python=3.8
  - conda-forge::ncurses
  - pip
  - pip:
    - ipykernel
    - ipython
    - numpy==1.23.5
    - pandas
    - scipy
    - requests
    - gymnasium
    - ray[default]==2.1.0
    - ray[rllib]
    - ray[serve]
    - ray[tune]
    - optuna
    - mlflow
    - torch==2.0.1
    - pytorch-lightning==1.8.4
    - scikit-learn
    - joblib
    - tqdm
    - seaborn
    - tensorboard
    - pyarrow
    - pyyaml
    - azure-core
    - azure-keyvault-secrets
    - azure-identity
    - azure-ai-ml
    - azureml-mlflow
    - azureml-inference-server-http
    - databricks-sql-connector
