FROM mcr.microsoft.com/azureml/minimal-ubuntu20.04-py38-cpu-inference:latest
ENV ACCEPT_EULA=Y

USER root
RUN apt update
RUN yes | apt upgrade
RUN apt dist-upgrade
RUN yes | apt install unattended-upgrades
RUN unattended-upgrade -d

RUN yes | apt-get purge openssh-client
RUN apt-get install git -y

WORKDIR /app
SHELL ["/bin/bash", "--login", "-c"]

ADD requirements.txt .

RUN conda create -n agent_py_env python=3.8
RUN echo "conda activate agent_py_env" > ~/.bashrc
RUN conda init bash
RUN conda update pip
ENV PYTHONPATH "/opt/miniconda/envs/agent_py_env/bin/python"
ENV PATH "$PYTHONPATH:$PATH"

RUN conda activate agent_py_env \
    && conda update pip \
    && pip install --no-cache-dir -i https://repo1.com/artifactory/api/pypi/pypi-virtual/simple/ -r requirements.txt
